icon_size=100
corner_radius=12
icon_alpha_start=100
icon_alpha_end=50
animation_duration=0.35
scale_factor=1.5
color=000000
outline_thickness=3
outline_color=FFFFFF
outline_alpha_start=100
outline_alpha_end=50
